### ISSUE TITLE
docs: istruzioni per sviluppo in locale

### ISSUE THREAD

**Issue by Pitasi** [pisa-dev/pisa.dev#34]
In questo momento il README.md è vuoto, mentre invece dovrebbe contenere le informazioni necessarie per chiunque voglia eseguire tutto lo stack in locale.

Sostanzialmente si tratta di:

- clonare la repo
- lanciare `npm install`
- lanciare un mysql in locale con docker: `docker run --name mysql -e MYSQL_ROOT_PASSWORD=secret -p 3309:3309 -d mysql`
- copiare `.env.example` in `.env`
- editare `.env` e settare la variabile `DATABASE_URL = 'mysql://root@127.0.0.1:3309/pisadev'`
- lanciare `npx prisma db push` per inizializzare un db vuoto
- eseguire `npm run dev` per eseguire Next.js in locale (l'app sarà disponibile su http://localhost:3000)

DoD:
- assicurarsi che le istruzioni scritte sopra funzionino
- modificare il file README.md per includerle (magari scritte in un modo più carino)

**Comment by LoSpiri** [comment]
Hi, I would love to help, can I work on this?

**Comment by Pitasi** [comment]
Certo, grazie! (Nelle discussioni/issue su GitHub scrivi pure in italiano se vuoi :))

Il codice invece di solito lo tengo solo in inglese per evitare troiai 😛
