### ISSUE TITLE
feat: jobs page

### ISSUE THREAD

**Issue by Pitasi** [pisa-dev/pisa.dev#36]
Al momento le offerte di lavoro possono essere visualizzate solamente sul canale Telegram https://pisajobs.t.me.

DoD:
- modificare `src/server/router/jobs.ts` per aggiungere una query tRPC che elenchi tutte le offerte di lavoro, ordinate per data di pubblicazione (decrescente). [Esempio](https://github.com/pisa-dev/pisa.dev/blob/4d8d2417a9c46e22bd9dc4efac1940dbad63f9b4/src/server/router/events.ts#L23-L24)
- creare una pagina https://pisa.dev/jobs (file: `src/pages/jobs/index.tsx`) dove elencare le offerte di lavoro ricevute dalla query tRPC (usare `const q = trpc.useQuery(["jobs.get-all"])` per effettuare la query)

È accettabile anche una pagina "senza stile" che contenga tutti i dati richiesti, per poi aggiungerci le classi CSS necessarie in seguito in una PR separata.

**Comment by giacomocusinato** [comment]
Posso farlo io, devo rispolverare un po' di React 😎
