### ISSUE TITLE
bug: job offers tags

### ISSUE THREAD

**Issue by Pitasi** [pisa-dev/pisa.dev#39]
Una JobOffer contiene dei tag:
https://github.com/pisa-dev/pisa.dev/blob/c4702fd518f44709e7269c5278e8c1a9fb0539eb/prisma/schema.prisma#L158

I tag sono inseriti dall'utente separati da virgole (`,`).

Il dato crudo dell'utente viene memorizzato nella colonna tagPretty:

https://github.com/pisa-dev/pisa.dev/blob/c4702fd518f44709e7269c5278e8c1a9fb0539eb/prisma/schema.prisma#L161

Il tagPretty viene passato a una semplice funzione di normalizzazione
https://github.com/pisa-dev/pisa.dev/blob/c4702fd518f44709e7269c5278e8c1a9fb0539eb/src/server/router/jobs.ts#L38

Questa funzione non gestisce spazi e altri caratteri speciali, che andrebbero cancellati.

C'è un altro piccolo bug nella funzione che genera il messaggio specifico per Telegram:
https://github.com/pisa-dev/pisa.dev/blob/c4702fd518f44709e7269c5278e8c1a9fb0539eb/src/server/router/jobs.ts#L139-L140
Viene utilizzata la versione "pretty" ma in realtà anche qui andrebbero gestiti gli spazi e gli altri caratteri speciali:
![image](https://user-images.githubusercontent.com/15048443/194307291-2838b287-a9d7-4c4d-b2e4-9d4856b33467.png)
![image](https://user-images.githubusercontent.com/15048443/194307395-93151dee-8cc6-467b-8e0a-225155f2dd71.png)

Andrebbe deciso se in questo caso usare direttamente la versione normalizzata invece di quella pretty.

**Comment by Wilkenfeld** [comment]
Buondì, se possibile vorrei fixare questo bug. Come preferite gestire i caratteri speciali? (per gli spazi possono andare bene degli underscore?)

**Comment by Pitasi** [comment]
Ciao @Wilkenfeld, grazie! :) 

Allora, io intanto distinguerei due funzioni:

- `normalizeTag(input)` -> tag normalizzato nel db
- `telegramEscapeTag(prettyTag)` -> tag "safe" per Telegram

La prima è già implementata ma non soddisfa tutti i casi:

```
normalizeTag("C#") == "c#"
normalizeTag("Event Sourcing") == "event sourcing"

# trimmiamo almeno gli spazi esterni
normalizeTag("   Event Sourcing") == "event sourcing"

# leviamo eventuali # iniziali
normalizeTag("#Bello") == "bello"
```

invece la seconda va implementata e usata, e darei in input direttamente il tag "pretty", magari sostituendo ai caratteri speciali gli underscore:

```
# caso speciale che possiamo gestire "a mano":
telegramEscapeTag("C#") == "#CSharp"

telegramEscapeTag("#hashtag") == "#hashtag"

telegramEscapeTag("altro#") == "#altro_"

telegramEscapeTag("   Event Sourcing") == "#Event_Sourcing"

telegramEscapeTag("CI/CD systems") == "#CI_CD_systems"
```

Spero di essere stato chiaro ma non esitare a chiedere :)
Intanto ti assegno questa issue!

**Comment by Wilkenfeld** [comment]
Va bene, butto giù una prima versione intanto.
